// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cores-alfaunipac/VarianteA.tsx": () => import("../components/mockups/cores-alfaunipac/VarianteA.tsx"),
  "./components/mockups/cores-alfaunipac/VarianteB.tsx": () => import("../components/mockups/cores-alfaunipac/VarianteB.tsx")
};
