export * from "./users";
export * from "./alunos";
export * from "./disciplinas";
export * from "./turmas";
export * from "./matriculas";
export * from "./chamadas";
export * from "./retencao";
export * from "./documentos";
export * from "./bap";
